### ISSUE TITLE
Cannot buid docker file for 2.13 version jmeter

### ISSUE THREAD

**Issue by ani-patel** [justb4/docker-jmeter#3] opened 2018-01-19 13:17 UTC

**Comment by ryanLeenay** [comment] 2018-11-08 23:49
Proably caused by mirror url choice 
mirrors.ocf.berkeley.edu/apache/jmeter/binaries/

Does not contain 2.13 version of jmeter.

**Comment by justb4** [comment] 2018-11-09 11:28
Closing, duplicate of #8.

**Closed as completed by justb4** 2018-11-09 11:28 UTC
Labels: bug
