### ISSUE TITLE
Link to verion 3.3 nolonger exists Now only 5.0

### ISSUE THREAD

**Issue by ryanLeenay** [justb4/docker-jmeter#8] opened 2018-11-05 23:19 UTC
Jmeter_Download_URL no longer contains default JMETER_VERSION=3.3. Also it appers 5.0 has some profomance changes

**Comment by pmouawad** [comment] 2018-11-06 06:08
Hello,
What do you mean by 5.0 has performance changes ?

Could you provide to the JMeter project more details ?

Thanks

**Comment by ryanLeenay** [comment] 2018-11-08 23:48
5.0 adds new behavior for http connections 

https://www.blazemeter.com/blog/what-is-new-jmeter-5

When checking link for download in mirrors.ocf.berkeley.edu/apache/jmeter/binaries/
I only see 5.0 in the mirror.

**Comment by justb4** [comment] 2018-11-09 11:18
Duplicate of #3. Found new mirror: https://archive.apache.org/dist/jmeter/binaries/ with archived releases, including 3.3. Will change in Docker file, but you can also build with the ENV var `JMETER_DOWNLOAD_URL`. 

Next we can see if we can upgrade to v5.0. Anyone willing to try and submit a PR for that?

**Comment by justb4** [comment] 2018-11-09 11:31
Also newly build Docker Images: https://hub.docker.com/r/justb4/jmeter/tags/

Closing, please open new issue for upgrades to later versions than 3.3.

**Closed as completed by justb4** 2018-11-09 11:31 UTC
Labels: bug
