### ISSUE TITLE
Getting error "jmeter requires the checksum of saveservice properties" while running the test 

### ISSUE THREAD

**Issue by nishant-shah-social** [justb4/docker-jmeter#24] opened 2019-10-16 05:20 UTC
Hi,
I have changed the test.sh file in order to include few jmeter parameters in the jmeter command.
But, when I try to execute, it gives me an error 
**Getting error "jmeter requires the checksum of saveservice properties" while running the test**

Any idea how to fix it? @justb4 
I am totally stuck for now.

Thanks,
Nishant Shah

**Comment by justb4** [comment] 2021-12-14 10:21
Closing, not clear what the issue is. Over two years old.
Cannot reproduce without details on local setup, e.g. what has been changed in `test.sh`.

**Closed as completed by justb4** 2021-12-14 10:21 UTC
Labels: invalid
